log syslog { warning, error, fatal };

include "constants.conf";

router id SOURCE4;

roa4 table rpki4;
roa6 table rpki6;

function rpki_invalid() {
    case net.type {
        NET_IP4: return roa_check(rpki4, net, bgp_path.last) = ROA_INVALID;
        NET_IP6: return roa_check(rpki6, net, bgp_path.last) = ROA_INVALID;
        else:    return false;
    }
}

protocol rpki {
  roa4 { table rpki4; };
  roa6 { table rpki6; };

  transport tcp;
  remote "rtr.rpki.cloudflare.com" port 8282;

  retry keep 90;
  refresh keep 900;
  expire keep 172800;
}

# Ignore interface events and the kernel routing table
protocol device {};
protocol kernel {};

template bgp ixp_rs {

template bgp ixp_rs4 from ixp_rs {
}
